myproject/urls.py
import os
#PROJECT_PATH = os.path.dirname(os.path.realpath(__file__))
#DOC_ROOT = os.path.join(PROJECT_PATH, '../ext_download')
#MEDIA_ROOT = '/home/vips/PersonalProject/focal/media'
from settings import MEDIA_ROOT
from django.conf.urls.defaults import *

#from focal_decocator import is_active

urlpatterns = patterns('',
    #for activity app
    (r'^$', 'activity.views.test_home'),
    #(r'^$', 'focaluser.views.home'),
    (r'^invite_request/$', 'focaluser.views.request_for_invite'),
    (r'^resend_invite/$', 'focaluser.views.resend_invite'),
    (r'^manage_invites/$', 'focaluser.views.invite_management'),
    (r'^generate_invite/$', 'focaluser.views.generate_new_invite'),
    (r'^register/$', 'focaluser.views.register'),
    (r'^authenticate/', 'focaluser.views.auth'),
    (r'^activate/', 'focaluser.views.activate'),
    (r'^login/', 'focaluser.views.login'),
    (r'^logout/', 'focaluser.views.logout'),
    url(r'^user_settings/', 'focaluser.views.user_settings', name="user_settings"),
    (r'^forgotpassword/', 'focaluser.views.forgot_password'),
    (r'^change_password/', 'focaluser.views.change_pasword'),
    (r'^confirm/', 'focaluser.views.confirm_email'),
    (r'^sharealink/$', 'activity.views.sharealink', {'act': 'in_activity'}),
    (r'^addtofav/$', 'activity.views.sharealink', {'act': 'in_favorite'}),
    (r'^context/(?P<act>[a-zA-Z0-9]+)/$', 'activity.views.test_home'),
    url(r'^context/(?P<actid>[a-zA-Z0-9]+)/manage/$', 'activity.views.activity_home', name="activity-settings"),
    (r'^user/(?P<u>[a-zA-Z0-9]+)/$', 'activity.views.test_home'),
    (r'^tag/$', 'activity.views.tag'),
    (r'^get_tags/$', 'activity.views.get_all_tags'),
    url(r'^discuss/(?P<linkid>[0-9]+)/$', 'activity.views.discuss', name="link-comment"),
    (r'^getcomment/$', 'tcomment.views.getcomment'),
    (r'^postcomment/$', 'tcomment.views.create_comment'),
    (r'^create/', 'activity.views.create_activity'),
    (r'^getlinkdetail/', 'activity.views.get_link_detail'),
    (r'^test_linkdetail/', 'activity.views.test_linkdetail'),
    (r'^link_status/', 'activity.views.get_link_page'),
    (r'^get_bookmarklet/', 'activity.views.get_bookmarklet'),
    (r'^referal/', 'activity.views.activity_referal_page'),
    (r'^act_frnd_invite/$', 'activity.views.activity_friend_invite'),
    (r'^reject_activity_invite/$', 'activity.views.reject_invitation'),
    #url(r'^activity/(?P<actid>[a-zA-Z0-9]+)/$', 'activity.views.activity_home', name="activity-settings"),
    url(r'^auth/(?P<service_name>[a-z]+)/$', 'activity.views.social_auth', name="social_auth"),
    #(r'^activity_setting/', 'activity.views.activity_settings'),
    url(r'^settings/', 'focaluser.views.account_settings', name='service_settings'),
    (r'^import_export/', 'activity.views.import_export'),
    url(r'^notification_settings/', 'focaluser.views.notification_settings', name='notification_settings'),
    url(r'^browser_plugins/', 'focaluser.views.browser_plugins', name='browser_plugins'),
    (r'^search/', 'search.views.search'),
    (r'^change_nickname/', 'focaluser.views.change_nickname'),
    (r'^change_name/', 'focaluser.views.change_name'),
    (r'^bulk_import/', 'activity.views.bulk_import'),
    (r'^import_from_file/', 'activity.views.bulk_import_from_file'),
    (r'^export/', 'activity.views.export'),
    (r'^site_notification/$', 'focaluser.views.site_notification'),
    (r'^sn_ack/(?P<notification_id>[0-9]+)/$', 'focaluser.views.sitenotification_ack'),
    (r'^redirect/', 'activity.views.redirect_link'),
    (r'^about/$', 'focaluser.views.about'),
    #rest
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}),
    #(r'^mailtest/', 'activity.views.test_mail'),
)

myproject/activity/models.py
from djangosphinx.models import SphinxSearch

from django.db import models
from url_encode import encode_url, decode_url
from settings import DOMAIN
from hashlib import sha1
import random
import urllib
from django.utils import simplejson as json
from datetime import datetime, timedelta
from time import gmtime, strftime
from tagging.models import Tag, TaggedItem
from myproject.focaluser.models import *

class LinkManager(models.Manager):
    def get(self, *args, **kwargs):
        if kwargs.get('link', None):
            kwargs['link_hash'] = sha1(kwargs['link']).hexdigest()
            kwargs.pop('link')
        try:
            return super(LinkManager, self).get_query_set().get(*args, **kwargs)
        except self.model.DoesNotExist:
            return None

    def get_or_create_link(self, *args, **kwargs):
        from myproject.my_html2txt import extract_title
        if kwargs['defaults']['title']=='':
            try:
                kwargs['defaults']['title'] = extract_title(kwargs['link']).strip()
            except:
                kwargs['defaults']['title'] = ''
        web_url, crtd = self.get_query_set().get_or_create(*args, **kwargs)
        return web_url, crtd

class Link(models.Model):
    #link = models.URLField(unique=True, max_length=255)
    link = models.TextField()
    link_hash = models.CharField(unique=True, max_length=255)
    title = models.TextField(blank=True)
    body = models.TextField(blank=True)
    meta_tags = models.TextField(blank=True)
    favicon = models.URLField(blank=True, null=True)
    thumb = models.URLField(blank=True, null=True)
    metadesc = models.TextField(blank=True, null=True)
    processed = models.BooleanField(default=False)

    search = SphinxSearch(
                            index='links_index delta',
                        )
    objects = LinkManager()

    def __unicode__(self):
        return '%d---%s'%(self.id, self.link)


class ActivityManager(models.Manager):
    def get(self, *args, **kwargs):
        try:
            return super(ActivityManager, self).get_query_set().get(*args, **kwargs)
        except self.model.DoesNotExist:
            return None

    def create_activity(self, activity_name, user, private=False):
        if not private:
            salt = sha1(str(random.random())).hexdigest()[:5]
            referal_code = sha1(salt + user.username + str(activity_name)).hexdigest()
        else:
            referal_code = None
        act, crtd = self.get_query_set().get_or_create(
                            activityname = activity_name,
                            created_by = user,
                            defaults = {
                                'private' : private,
                                'referal_code': referal_code
                            }
                        )
        if crtd:
            ar = ActivityReferal.objects.get_or_create(activity=act)
            am = ActivityMember.objects.create_activity_member(act, user)
        return act, crtd


class Activity(models.Model):
    activityname = models.CharField(max_length=50)
    created_on = models.DateTimeField(auto_now=False, auto_now_add=True)
    private = models.BooleanField(default=False)
    created_by = models.ForeignKey(ActUserProfile)
    active = models.BooleanField(default=True)
    view_mode = models.CharField(max_length=10, default='none')
    ipaddress = models.IPAddressField(blank=True, null=True)
    referal_code = models.CharField(max_length=500, blank=True, null=True)

    objects = ActivityManager()

    def get_activity_dict(self):
        return {'id': self.id, 'name': self.activityname, 'created_by':self.created_by.username}
    def get_referal_url(self):
        return '%s/referal/?code=%s'%(DOMAIN, self.referal_code)
    def get_activity_key(self):
        return encode_url(self.id)
    def get_activity_id(self, activity_key):
        return decode_url(activity_key)


class ActivityReferal(models.Model):
    activity = models.ForeignKey(Activity)
    view_count = models.PositiveIntegerField(default=0)
    conversion = models.PositiveIntegerField(default=0)
    expired = models.BooleanField(default=False)
    
    def increment_viewcount(self):
        self.view_count += 1
        self.save()

class ActivityLinkManager(models.Manager):
    def get_activities_of_link(self, linkobj):
        return [al.activity for al in self.get_query_set().filter(actlink=linkobj, deleted=False)]

    def get_links_of_activity(self, activity, num=20):
        al = self.get_query_set().filter(activity=activity, deleted=False).values('actlink_id').order_by('submited_on')[:num]
        links = []
        for i in al:
            link = i.get('actlink_id', None)
            if link: links.append(link)
        return Link.objects.filter(id__in=links)

    def sharealink(self, activity, web_url, user):
        shared = False
        al, crtd = self.get_query_set().get_or_create(
                            activity = activity,
                            actlink = web_url,
                            defaults = {
                                'linktitle': web_url.title.strip(),
                                'submited_by': user
                            }
                        )
        if not crtd:
            if al.deleted:
                al.deleted = False
                al.deleted_on = None
                al.submited_on = datetime.now()
                al.save()
        
        shared = True

        if activity.activityname in ['Share on Twitter', 'Read It Later', 'Share on Facebook']:
            ssq = SocialShareQueue.objects.create(user=user, url=web_url, activityname=activity.activityname)
        elif activity.activityname!='Personal':
            param = { 'link': web_url, 'by': user, 'activity': activity, 'submited_on': al.submited_on}
            r = ActivityMember.objects.send_mail_to_activity_member(al, param, 'new_link')
        else:
            pass

        return al, shared

    def can_delete(self, activity, link, user):
        try:
            return self.get_query_set().get(activity=activity, actlink=link, submited_by=user)
        except:
            return False

    def delalink(self, activity, link, user):
        ret = self.can_delete(activity, link, user)
        if ret:
            ret.deleted = True
            ret.deleted_on = datetime.now()
            ret.save()
            return json.dumps({'status':1, 'message':'successfully deleted'})
        else:
            return json.dumps({'status':0,'message':'you can only delete links you have shared'})

    def export(self, user):
        user_activities = ActivityMember.objects.get_user_activity(user)
        from collections import defaultdict
        d = defaultdict(lambda: set())
        for i in self.get_query_set().filter(activity__in=user_activities):
            d[i.activity].add(i.actlink)
        return dict(d)

    def get_link_detail(self, link_obj, user):
        ret = {'status': 'ok', 'message': None, 'activities': [], 'favorite': False, 'tags': [], 'suggested_tags': [], 'tag_set': []}
        ret_val = []
        for ua in ActivityMember.objects.get_user_activity(user):
            if link_obj is None:
                d = {"id": ua.id, "name": ua.activityname, "members":[], "order": 1, "added":False, "can_delete": True, "by": None}
                d["members"] = [m.nickname for m in ActivityMember.objects.get_activity_member(ua)]
                ret_val.append(d)
            else:
                if ua.activityname=='Personal':
                    fav = self.get_query_set().filter(activity=ua, actlink=link_obj, deleted=False)
                    if len(fav)==1:
                        ret['favorite'] = True
                        ret['tags'] = [i.name for i in Tag.objects.get_for_object(fav[0])]
                else:
                    d = {"id": ua.id, "name": ua.activityname, "members":[], "order": 1, "added":False, "can_delete": True, "by": None}
                    d["members"] = [m.nickname for m in ActivityMember.objects.get_activity_member(ua)]
                    r = self.get_query_set().filter(activity=ua, actlink=link_obj, deleted=False)
                    if len(r)==1:
                        d["added"] = True
                        if r[0].submited_by!=user:
                            d["can_delete"] = False
                        d["by"] = r[0].submited_by.nickname
                    ret_val.append(d)
        ret['activities'] = filter(lambda x: x.get('name') not in ['Personal', 'Focal Tips'], ret_val)
        return ret


class ActivityLink(models.Model):
    actlink = models.ForeignKey(Link)
    activity = models.ForeignKey(Activity)
    linktitle = models.CharField(max_length=500, blank=True, null=True)
    submited_by = models.ForeignKey(ActUserProfile)
    submited_on = models.DateTimeField(auto_now=False, auto_now_add=True)
    deleted = models.BooleanField(default=False)
    deleted_on = models.DateTimeField(blank=True, null=True)
    ipaddress = models.IPAddressField(blank=True, null=True)
    note = models.TextField(max_length=1000, blank=True, null=True)
    reference = models.TextField(max_length=1000, blank=True, null=True)

    objects = ActivityLinkManager()

    class Meta:
        unique_together = (("activity", "actlink"),)


#tagging on ActivityLink objects
import tagging
try:
    tagging.register(ActivityLink)
except tagging.AlreadyRegistered:
    pass


def _sort_activity(a, b):
    if a.link_count<b.link_count: return 1
    if a.link_count==b.link_count: return 0
    if a.link_count>b.link_count: return -1

class ActivityMemberManager(models.Manager):
    def get_user_activity(self, user):
        try:
            return user.activities
        except:
            from django.db.models import Count
            d = {}
            user_activity_id = [i['activity_id'] for i in user.activitymember_set.values()] # + [i['id'] for i in user.activity_set.values()]

templates/activity_home_ajax.html
{%load get_friends%}
{%load has_invitation_sent%}
<h2 class="headSmall hide"></h2>
<h2 class="headBig">
	{{activity.activityname}}
</h2>
<ul class="subLinks">
	<li><a href="#/context/{{activity.get_activity_key}}">Links</a></li>
	<li>Members</li>
	{# <li><a href="#">Members</a></li> #}
</ul>

<div id="entry_container">
<div class="activity_info">
	<!-- <span class="width150">Creation Date : </span> {{activity.created_on}} <br />
    <span class="width150">Created By : </span> {{activity.created_by.nickname}} <br />
    <span class="width150">Total Links : </span> {{activity_link|length}} <br /> -->
    <h4 class="impact">Members</h4>
    {%for u in activity_member%}
        <a href="#/user/{{u.get_user_key}}">{{u.nickname}}</a>{%if not forloop.last%}, {%endif%}
    {%endfor%}
    <br />
	{%if not activity.private%}
        {%ifequal activity.created_by user%}
        <h4 class="impact">Invite Friends</h4>

        <h5 class="subHeadText" id="invite_friend_head">Invite Users already connected with you on Focal</h5>
        <ul id="invite_friend_list">
            {% friends of user%}
            {% for u, count in friends %}
                {% if u not in activity_member %}
                {% ifnotequal u.email 'help@focal.io' %}
                    {%has_invitation_sent to u for activity%}
                    <li>
                        <span class="user">{{u.nickname}}</span> 
                        {% if not invitation_sent %}
                        <em>
                            <a class="link_invite_friends" href="#" user_key="{{u.get_user_key}}" context_key="{{activity.get_activity_key}}">Invite</a>
                        </em>
                        {% else %}
                        <em>
                            <span class="to-delete"><img src="/site_media/img/1303821038_OK.png" /> Invitation Sent &nbsp; &nbsp; </span>
                            <a class="link_invite_friends" href="#" user_key="{{u.get_user_key}}" context_key="{{activity.get_activity_key}}">Resend Invitation</a>
                        </em>
                        {% endif %}
                    </li>
                {% endifnotequal %}
                {% endif %}
            {% endfor %}
        </ul>
        <script type="text/javascript">
            if($("#invite_friend_list li").length == 0){
                $("#invite_friend_list").hide();
                $("#invite_friend_head").hide();
            }
        </script>
        <h5 class="subHeadText">Invite Users who are not members of Focal</h5>
        <div class="gray_bg">
            Just send this following <b>referal link</b> to your friend. <br />
            <input id="txt_link" readonly="readonly" onclick="this.focus();this.select();return false;" style="margin-top:5px;font-size:14px;width:75%;" type='text' value="{{activity.get_referal_url}}" />
            <input onclick="$('#txt_link').focus();$('#txt_link').select();" type="button" class="button" value="Select Link" />
        </div>
        {%endifequal%}
   {%else%}
		
   {%endif%}      
</div>
</div>
<script type="text/javascript">
    $('.link_invite_friends').click(function(e){
        e.preventDefault();e.stopPropagation();
        $('<img />',{
            'src':'/site_media/img/small-load.gif',
            'style':"margin-left:5px;vertical-align:middle"
        }).appendTo($(this).parent());
        var link = $(this);
        $('.to-delete',link.parent()).remove();
        $.ajax({
            'url':'/act_frnd_invite/',
            'type':'POST',
            'data':'activity_key='+link.attr('context_key')+'&friend_key='+link.attr('user_key'),
            success: function( data ) {
                link.html('Resend Invitation')
                $('img', link.parent()).remove();
                $('<span />',{
                    'class':'to-delete',
                    'html':'<img src="/site_media/img/1303821038_OK.png" /> Invitation Sent &nbsp; &nbsp; '
                }).prependTo(link.parent());
            }
        })
        
    });
</script>

templates/activity_settings.html
{% extends "base.html" %}

{%load get_domain%}

{% block title %}Your Activity Settings : {% endblock %}

{% block content %}
    <div class="leftSidebar">
        <h4 class="blue">Contexts <a href="#" class="add_context" title="Create new Context">Add New Context</a></h4>        
    </div>    
    <div class="rightContent">
        
        <h2>Your Bookmarks</h2> 
        {%for act in all_user_activity%}
            <div class="entry"> 
                <h3 class="title">
                    {% if act.activityname == "Share on Twitter" %}
                      {% if actuser.twitter_access_token %}
                        {{act.activityname}}<a href="?activityname={{act.activityname}}"><em> {{actuser.twitter_access_token }}</em></a>
                      {% else %}
                        {{act.activityname}}<a href="?activityname={{act.activityname}}"> <em> set your twitter account</em></a>
                      {% endif %}
                    {% else %} {% if act.activityname == "Share on Facebook" %}
                      {% if actuser.facebook_access_token %}
                        {{act.activityname}}<a href="https://graph.facebook.com/oauth/authorize?client_id=146906412044571&redirect_uri=http://www.focal.io/auth/facebook/?scope=offline_access,publish_stream"><em> {{actuser.facebook_access_token }}</em></a>
                        <!--{{act.activityname}}<a href="?activityname={{act.activityname}}"><em> {{actuser.facebook_access_token }}</em></a>-->
                      {% else %}
                        {{act.activityname}}<a href="https://graph.facebook.com/oauth/authorize?client_id=146906412044571&redirect_uri=http://www.focal.io/auth/facebook/?scope=offline_access"><em> set your facebook account</em></a>
                      {% endif %}
                    {% else %}
                      {{act.activityname}}<a href="/activity/{{act.id}}/"><em> setting</em></a>
                    {% endif %}{% endif %}
                </h3>
            </div> 
        {%endfor%}
    </div>
{% endblock %}

templates/createactivity.html
{% extends "base.html" %}

{% block content %}
<div class='left60'>
  <form method="POST"> {% csrf_token %}

    <h2>Create an Activity</h2> 
    <label for="activity">Activity Name</label> <input type="text" id="activity" name="activity" value="" />
    {% if error %}
        <br /><div class="message">{{error}}</div>
    {% endif %}
    <br /><br />
    <input class='button big gray' type="submit" value="Create Activity" />

  </form> 
</div>
<div class='right40'>
  <h3>Other Activities</h3>
  <ul>
  {%for i in user.activities%}<li><a href="/activity/{{i.get_activity_key}}/">{{i.activityname}}</a> ({{ i.activitylink_set.values|length }} bookmarks)</li> {%endfor%}    
  </ul>
</div>
<div class="clearfix"></div>
{% endblock %}

templates/early_invite.html
The wait is over! , here's an early invite for the focal beta.<br/><br/>

<a href="{{invite_link}}">{{invite_link}}</a><br/><br/>


Focal is still under beta. Things might be crashing now and then but we have it under control. Go give it a spin ,it'd be great if you could give us some feedback too :) <br/><br/>

we're here to help , write to us if you need help:  help@focal.io<br/><br/>

so long!<br/>
focal team.<br/>

templates/instapaper_login_page.html
{{mesg}}
<form method="POST" action="/auth/instapaper/">
<input type="text" name="username" id="username_id">
<input type="password" name="password" id="password_id">
<input type="submit" name="submit">
</form>

templates/join_activity.html
{% extends "home_base.html" %}


{%load get_domain%}

{% block title %}Context Invitation : {% endblock %}

{% block content %}
    
    <div class="center_content">
        <h2 class="focus_head">
            <u>{{activity.created_by.nickname}}</u> Invited you to join this context
        </h2> 
        <div class="context_name left60">
            <h3>{{activity.activityname}}</h3>
            <p>{{activity.activitylink_set.count}} links, {{activity.activitymember_set.count}} {{activity.activitymember_set.count|pluralize:"member,members" }}</p>
        </div>
        <div class="join_context right40">
            <input id="join_button" type='button' class="button" value="Join Context" onclick="show_hidden_buttons(this);" />
            <div id="hidden_buttons">
                <input data-controls-modal="div_register_context" data-backdrop="true" data-keyboard="true" id="signup_button" type='button' class="button signup" value="Sign Up" />
                <input data-controls-modal="div_login_context" data-backdrop="true" data-keyboard="true" id="login_button" type='button' class="button signin" value="Sign In" />
            </div>
        </div>
        
        <h4 class="left80">Recent Activity</h4>
        <h4 class="right20">Members</h4>
        <div class="green-bg">
            <ul class="left80">
            {% if activity_links %}
                {% for lnk in activity_links|slice:":8" %}
                    <li>
                        <a href='{{lnk.link}}' title="{{lnk.title}}"><img src="{{lnk.favicon}}" class="favi" /></a>
                        <a href='{{lnk.link}}' title="{{lnk.title}}">{{lnk.title}}</a> 
                    </li>
                {%endfor%}
            {% else %}
                <li>No links shared in this context</li>
            {% endif %}
            </ul>
            <ul class="right20">
                <!-- <li>{{activity.created_by.nickname}}</li> -->
                {%for m in activity.activitymember_set.all|slice:":5"%}
                <li>{{m.member.nickname}}</li>
                {%endfor%}
                
            </ul>
            <div class="clearfloat"></div>
        </div>

        <p class="tagline">
            <span>Contexts</span> are a gr8 way to share links within a group. Organize, Share, Discover links with Focal. 
        </p>

        <!-- <p class="text_align big-text-black">Use these simple tools to get started</p> -->
        
        <div class="modal hide fade" id="div_register_context">
        <form id='context-join_form' class="context-form" method="POST">
            <div class="modal-header">
                <a href="#" class="close">&times;</a>
                <h3>Sign Up to Join</h3>
            </div>
            <div class="modal-body">
             {% csrf_token %}
            <input type="hidden" name="referalcode" value="{{activity.referal_code}}" id="id_referalcode" />
            <fieldset>
                <div class="box_content">
                    <p>
                        <div class="left50">
                            <label for="first_name_id">First Name : </label>
                            <input  id="first_name_id" type="text" name="first_name" class="required" />
                        </div>
                        <div class="right50">
                            <label for="last_name_id">Last Name : </label>
                            <input  id="last_name_id" type="text" name="last_name" class="required" />
                        </div>
                        <div class="clearfloat"></div>
                    </p>
                    <p>
                        <label for="nickname">Nick Name : </label>
                        <input id="nickname" type="text" name="nickname"  class="required" />
                        <div class="help_text">Name by which other users will know you.</div>
                    </p>
                    <p>
                    	<label for="email_id">Email : </label>
                    	<input  id="email_id" type="text" name="email" class="required big-textbox" />
                    </p>
                    <p>
                    	<label for="pass1">Password : </label>
                    	<input id="pass1" type="password" name="pass1" class="required big-textbox" />
                    </p>
                </div>
            </fieldset>
            <div class="message hide"></div>
            </div>
            <div class="modal-footer">
                Already a Member ? 
                <a href="javascript:void(0);" onclick="$('#div_register_context').modal('hide');$('#login_button').trigger('click');">Sign In</a>
                
                <input class='button primary' type="submit" value="Register &amp; Join Activity" />
                <img src="/site_media/img/load.gif" alt="" class="hide loader" />
            </div>
        </form>
        </div>
        <div class="modal hide fade" id="div_login_context">
        <form id='context-login_form' class="context-form" method="POST">
            <div class="modal-header">
                <a href="#" class="close">&times;</a>
                <h3>Sign In to Join</h3>
            </div>
            <div class="modal-body">
                {% csrf_token %}
                <input type="hidden" name="referalcode" value="{{activity.referal_code}}" id="id_referalcode" />
                <fieldset>
                    <div class="box_content">
                        <p>
                        	<label for="email_id1">Email : </label>
                        	<input  id="email_id1" type="text" name="email" class="big-textbox" value="{{email}}" />
                        </p>
                        <p>
                        	<label for="pass">Password : </label>
                        	<input id="pass" type="password" name="password" class="big-textbox"/>
                        </p>
                    </div>
                </fieldset>
                <div class="message hide"></div>
            </div>
            <div class="modal-footer">
                <a style="" href="/forgotpassword/">Forgot Password</a>
                <a href="javascript:void(0);" onclick="$('#div_login_context').modal('hide');$('#signup_button').trigger('click');">Sign-up</a>
                
                <input class='button primary' type="submit" value="Sign In &amp; Join Activity" />
                <img src="/site_media/img/load.gif" alt="" class="hide loader" />
            </div>
        </form>
        </div>
            
        <!--
        <form id='join_form' method="POST"> {% csrf_token %}
        <fieldset>
            {%if actuser.id%}
                <label for="email">email id</label> <input style="width:200px;"  type="text" id="email_id" name="email" value="{{actuser.email}}" readonly="readonly"/>
                <input type="hidden" name="referalcode" value="{{activity.referal_code}}" id="id_referalcode" />
                <p class="submit"><input class='button bigrounded gray' type="submit" value="Join Activity" /></p>
            {%else%}
                <label for="email">email id</label> <input type="text" id="email_id" name="email" value="{{email}}" />
                <p><label for="pass1">password</label> <input type="password" class="inputtext" name="password" id="pass"></p>
                <input type="hidden" name="referalcode" value="{{activity.referal_code}}" id="id_referalcode" /><br />
                <p class="submit"><input class='button bigrounded gray' type="submit" value="Join Activity" /></p>
            {%endif%}
        </fieldset>
        </form> -->
        <!--
        <form id='join_form' method="POST"> {% csrf_token %}
        <fieldset>
            <p><label for="email">email id</label> <input style="width:200px;"  type="text" id="email_id" name="email" value="{{email}}" /></p>
            <p><label for="pass1">password</label> <input type="password" class="inputtext" name="pass1" id="pass1"></p>
            <p><label for="pass2">re password</label> <input type="password" class="inputtext" name="pass2" id="pass2"></p>
            <input type="hidden" name="referalcode" value="{{activity.referal_code}}" id="id_referalcode" /><br />
            <p class="submit"><input class='button bigrounded gray' type="submit" value="Join Activity" /></p>
        </fieldset>
        </form>
        <br />
        <h4>Already a member of focal, join this activity</h4>
        -->
    </div>
    <br /><br />
{% endblock %}

{% block css %}
<style type="text/css">
#wrap{
    background: white !important;
}
</style>
{% endblock %}

{% block js %}
<script type="text/javascript" src="/site_media/js/jquery-validation-1.8.1/jquery.validate.js"></script>
<script type="text/javascript">
function show_hidden_buttons(button){
    $(button).animate({
        opacity: 0,
        right: '-200'
    }, 200, function(){
        $(button).css('display','none');
        $('#hidden_buttons').css('display','block').animate({right:-170,opacity:1},200);
    });
}
$(document).ready(function(){
    $("#first_name_id, #last_name_id").live('keyup blur', function(){
        $("#nickname").val($("#first_name_id").val().slice(0,1).toUpperCase() + $("#first_name_id").val().slice(1) + $("#last_name_id").val().slice(0,1).toUpperCase());
    });
    $("#join_form").validate({
      rules: {
        password: "required"
      }
    });

    $("form.context-form").submit(function(){
        var frm = $(this);
        $('.loader',frm).removeClass('hide');
        $('.message',frm).addClass('hide').html('');
        $.ajax({
            url: '/referal/?is_ajax=true',
            type: 'post',
            dataType: 'json',
            data: frm.serialize(),
            success: function(obj){
                $('.loader',frm).addClass('hide');
                if(obj.status == 1){
                    message = "You're done !!";
                    window.location = obj.next;
                    $('.message',frm).removeClass('error');
                    $('#'+frm.attr('modal')).modal('hide')
                }else{
                    message = obj.message;
                    $('.message',frm).addClass('error');
                }
                $('.message',frm).html(message).removeClass('hide');
            }
        });
        return false;
    })
});
</script>
{% endblock %}